outputs: "./outputs"
dev: false

http:
  host: '0.0.0.0'
  port: 13000

cluster:
  scheduler_port: 8786
  dashboard_address: ':8787'
  n_workers: 2  # 启动的进程数
  threads_per_worker: 1  # 每个进程的线程数

log:
  path: './logs'
  # 日志模块会为 filename 添加相应的后缀
  # 在模板中: filename: '{{ project_name|replace(' ', '_') }}'
  filename: 'py_project_template'
  level: 'info'
  rotation: '1 days'
  retention: '5 days'
  format: '<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> - <blue>[{process.id}]</blue> - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>'

# prefect section: {%- if prefect_server_url %}
# prefect:
#   server_url: "{{ prefect_server_url }}"
#   api_url: "{{ prefect_api_url }}"
#   work_pool: "{{ prefect_work_pool }}"
# {%- endif %}
